# Generated by Django 5.1.4 on 2025-01-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_detallefactura_precio_unitario_factura_iva_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
