# Generated by Django 5.1.4 on 2025-01-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_alter_categoria_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('ruc', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
